language: php

php:
  - 5.3
  - 5.4
  
env:
  - SYMFONY_VERSION=2.0.*
  - SYMFONY_VERSION=2.1.*
  - SYMFONY_VERSION=2.2.*
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=dev-master
  
before_script:
  - composer require symfony/http-kernel:${SYMFONY_VERSION} --no-update
  - composer require symfony/config:${SYMFONY_VERSION} --no-update --dev
  - composer install --dev

script:
  - phpunit --coverage-text  